modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "too_many_bows"
version = "${version}"
displayName = "Too Many Bows"
authors = "Bandit-Bytes"
description = '''
Too Many Bows!! Strong amazing bows!
'''
#logoFile = ""

[[dependencies.too_many_bows]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_bows]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_bows]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
